### ISSUE TITLE
Тогда уж кнопку дизлайков надо отключать (атрибут disabled), чтобы пользователь не думал, что это ошибка вашего приложения

### ISSUE THREAD

**Issue by coursar** [BlackRider116/CreatingPosts#2]
https://github.com/BlackRider116/CreatingPosts/blob/1fbd661526050aa5298117638805f1ced9cf0440/app.js#L91

И не забудьте потом включить обратно, когда можно будет дизлайкать.

**Comment by BlackRider116** [comment]
согласен) опять я что то от себя добавил) удалил это условие.
